spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gallexiv?useSSL=false&serverTimezone=UTC
    username: benny
    password: benben327327
  security:
    user:
      name: admin
      password: admin1234
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      password: benben327327
server:
  port: 8080
  servlet:
    # http(s)://(子網域名.)網域名.主域/context-path/(api/end-point)
    context-path:
gallexiv:
  upload:
    rootpath: D:/gallexiv/upload
#  網域用,分隔 改用 Security 之後可能不用這兩個 allow 設定了
# TODO 測試移除
#  allowedOrigins: "http://localhost:3100"
#  allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"