spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gallexiv_v3?useSSL=false&serverTimezone=UTC
    username: benny
    password: benben327327
  security:
    user:
      name: admin
      password: admin1234
  data:
    redis:
      host: 192.168.0.205
      port: 6379
      database: 1
      password: benben327327
server:
  port: 8080
  servlet:
    context-path: # 可以用來區分的 API 的 版本 # http(s)://(子網域名.)網域名.主域/context-path/(api/end-point)
gallexiv:
  upload:
    rootpath: D:/gallexiv